### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by gcavalcantes** [gcavalcantes/ModGerenciador#2]
## Implementação
**PRECISA ESTAR PRONTA ATÉ DIA 02/05!!**
### Desenvolvimento
- [x] Criar um mapa lógico das classes e dos métodos do projeto.
- [x] Criar as classes (levar em conta os critérios).
- [x] Criar os esqueletos dos métodos requiridos.
- [x] Método de inicialização da Tabela de Símbolos.
- [x] Método de busca de um elemento.
- [x] Método de inserção.
- [x] Método de deleção.
- [x] Método de atualização (alteração).

**Comment by gcavalcantes** [comment]
Todos os critérios foram atingidos. Isso fechado.
